# Python CircleCI 2.0 configuration file
# Details: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ~/app && sudo pip3 install -r requirements.txt
      - run:
          name: Use default (dist) config.ini
          command: cd ~/app && cp config.ini.dist config.ini
      - run:
          name: SSH access for unknown host
          command: git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
      - run:
          name: Run Tests
          command: cd ~/app && python3 app/test.py

  deploy-job:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Add dokku remotely
          command: git remote add dokku dokku@$SERVER_IP:cn-back
      - run:
          name: Deploy via dokku
          command: git push dokku master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master